version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ilyashbil8
      POSTGRES_DB: gapAtica
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_api
    restart: always
    depends_on:
      - db
    ports:
      - "4001:4001"
    environment:
      PG_USER: postgres
      PG_PASSWORD: ilyashbil8
      PG_HOST: db  
      PG_DATABASE: gapAtica
      PG_PORT: 5432

volumes:
  postgres_data: